"""Build exact-version shader metadata from SHA-1-verified official clients.

Network access is explicit and release-time only. The generated module contains
asset names and interface facts, never shader implementations or client jars.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import hashlib
import json
from pathlib import Path
import pprint
import shutil
import urllib.request
import zipfile

MANIFEST = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"


def get_json(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def inspect_client(path, version, download):
    with zipfile.ZipFile(path) as archive:
        files = sorted(n for n in archive.namelist() if n.startswith("assets/minecraft/shaders/") and not n.endswith("/"))
        modern = "assets/minecraft/post_effect/entity_outline.json"
        legacy = "assets/minecraft/shaders/post/entity_outline.json"
        graph_path = modern if modern in archive.namelist() else legacy
        graph_bytes = archive.read(graph_path)
        graph = json.loads(graph_bytes)
        first = graph["passes"][0]
        schema = "direct" if "vertex_shader" in first else "program" if "program" in first else "legacy"
        internal = json.loads(archive.read("version.json"))
        fmt = internal["pack_version"]
        resource = fmt if isinstance(fmt, int) else fmt.get("resource", fmt.get("resource_major"))
        minor = 0 if isinstance(fmt, int) else fmt.get("resource_minor", 0)
        block_uniforms = any(isinstance(p.get("uniforms"), dict) for p in graph["passes"])
        vertex_ids = False
        if schema == "direct":
            vertex = first["vertex_shader"].removeprefix("minecraft:")
            vertex_ids = "gl_VertexID" in archive.read(f"assets/minecraft/shaders/{vertex}.vsh").decode()
        return {"client_sha1": download["sha1"], "resource_format": resource,
                "resource_minor": minor, "post_schema": schema, "uniform_blocks": block_uniforms,
                "post_vertex_id": vertex_ids, "core_shaders": any("/shaders/core/" in n for n in files),
                "post_graph": graph_path, "post_graph_sha256": hashlib.sha256(graph_bytes).hexdigest(),
                "shader_files": files}


def inventory(version, entry, cache):
    output = cache / f"{version}.json"
    if output.exists():
        return version, json.loads(output.read_text(encoding="utf-8"))
    metadata = get_json(entry["url"])
    download = metadata["downloads"]["client"]
    existing = cache.parent / f"client-{version}" / "client.jar"
    path = existing if existing.is_file() else cache / f"{version}.jar"
    temporary = path != existing
    try:
        if not path.exists():
            with urllib.request.urlopen(download["url"], timeout=60) as response, path.open("wb") as destination:
                shutil.copyfileobj(response, destination)
        with path.open("rb") as stream:
            digest = hashlib.file_digest(stream, "sha1").hexdigest()
        if digest != download["sha1"]:
            raise ValueError(f"{version}: client SHA-1 mismatch")
        data = inspect_client(path, version, download)
        output.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        return version, data
    finally:
        # Only the single temporary jar created by this importer is removed.
        if temporary:
            path.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--versions", nargs="+", required=True)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.cache.mkdir(parents=True, exist_ok=True)
    entries = {v["id"]: v for v in get_json(MANIFEST)["versions"]}
    if any(v not in entries for v in args.versions):
        parser.error("All requested versions must exist in the official manifest")
    profiles = {}
    with ThreadPoolExecutor(max_workers=3) as pool:
        futures = [pool.submit(inventory, v, entries[v], args.cache) for v in args.versions]
        for future in as_completed(futures):
            version, data = future.result()
            profiles[version] = data
            print(f"{version}: format={data['resource_format']}.{data['resource_minor']} schema={data['post_schema']} blocks={data['uniform_blocks']} vertex_id={data['post_vertex_id']}", flush=True)
    header = '"""Official client metadata, extracted after download SHA-1 verification.\nGenerated by dcore.release.shader_inventory; no shader implementations.\n"""\n\n'
    args.output.write_text(header + "PROFILES = " + pprint.pformat(profiles, width=110, sort_dicts=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
